# docker-compose.yml
version: '3'
services:
  app:
    build: .
    container_name: notification-api
    ports:
      - "8080:8080"
    # volumes:
    #   - .:/app
    depends_on:
      - redis
  redis:
    image: redis:7
    container_name: redis-server
    ports:
      - "6379:6379"
